### ISSUE TITLE
0.2.29报java.lang.RuntimeException: setParameters failed

### ISSUE THREAD

**Issue by Mars163** [MingYueChunQiu/RecorderManager#15]
在某些设备上无法录像，报错：
    Process: com.hengkai.intelligentpensionplatformservice, PID: 4796
    java.lang.RuntimeException: setParameters failed
        at android.hardware.Camera.native_setParameters(Native Method)
        at android.hardware.Camera.setParameters(Camera.java:3081)
        at com.mingyuechunqiu.recordermanager.feature.record.RecorderManager.initCameraParameters(RecorderManager.java:281)
        at com.mingyuechunqiu.recordermanager.feature.record.RecorderManager.initCamera(RecorderManager.java:177)
        at com.mingyuechunqiu.recordermanager.feature.main.detail.RecordVideoPresenter.startPreview(RecordVideoPresenter.java:93)
        at com.mingyuechunqiu.recordermanager.feature.main.detail.RecordVideoPresenter.onSurfaceCreated(RecordVideoPresenter.java:383)
        at com.mingyuechunqiu.recordermanager.feature.main.detail.RecordVideoFragment.surfaceCreated(RecordVideoFragment.java:197)
        at android.view.SurfaceView.updateWindow(SurfaceView.java:675)
        at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:202)
        at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2348)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1292)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6598)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:800)
        at android.view.Choreographer.doCallbacks(Choreographer.java:603)
        at android.view.Choreographer.doFrame(Choreographer.java:572)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:786)
        at android.os.Handler.handleCallback(Handler.java:815)
        at android.os.Handler.dispatchMessage(Handler.java:104)
        at android.os.Looper.loop(Looper.java:194)
        at android.app.ActivityThread.main(ActivityThread.java:5637)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by MingYueChunQiu** [comment]
能告知一下是什么牌子机型的手机？是直接通过RecorderManagerFactory.getRecordVideoRequest().startRecordVideo(MainActivity.this, 0);这样调用出现问题的吗？

**Comment by Mars163** [comment]
一个杂牌山寨平板，就直接集成RecordVideoFragment打开页面的时候报的。
1、我把mCamera.setParameters(parameters); 
改成：
try {
            mCamera.setParameters(parameters);
        } catch (Exception e) {
            //非常罕见的情况
            //个别机型在SupportPreviewSizes里汇报了支持某种预览尺寸，但实际是不支持的，设置进去就会抛出RuntimeException.
            e.printStackTrace();
            try {
                //遇到上面所说的情况，只能设置一个最小的预览尺寸
                parameters.setPreviewSize(1920, 1080);
                mCamera.setParameters(parameters);
            } catch (Exception e1) {
                //到这里还有问题，就是拍照尺寸的锅了，同样只能设置一个最小的拍照尺寸
                e1.printStackTrace();
                try {
                    parameters.setPictureSize(1920, 1080);
                    mCamera.setParameters(parameters);
                } catch (Exception ignored) {
                }
            }
        }

2、然后下面mCamera.startPreview();偶尔也会抛出RuntimeException，不是每次打开都抛，catch的IOException捕捉不到，会崩。

3、如果我在录制视频的时候，设置了设备不支持的videoWidth和videoHeight时，在RecorderHelper里面的mRecorder.start(); 这行也会抛出RuntimeException，catch不到也会崩。

**Comment by MingYueChunQiu** [comment]
……针对这款机型，每个支持的尺寸都试过了吗，看能写个demo测试一下吗,先获取到所有支持的从高到低排好序的PreviewSize与PictureSize，库里面 CameraParamsUtils这个类有方法可以获取，然后再循环while（paramsError）{按你上面的代码，每次按顺序选一个进行设置，直到不报错为止}，看看是否能在设备所支持的大小里选择到最高质量且能正常使用的尺寸。
