### ISSUE TITLE
小米6崩溃

### ISSUE THREAD

**Issue by mofei031026** [MingYueChunQiu/RecorderManager#2]
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.geographysurvey, PID: 26848
    java.lang.RuntimeException: setParameters failed
        at android.hardware.Camera.native_setParameters(Native Method)
        at android.hardware.Camera.setParameters(Camera.java:2058)
        at com.mingyuechunqiu.recordermanager.record.RecorderManager.initCameraParameters(RecorderManager.java:204)
        at com.mingyuechunqiu.recordermanager.record.RecorderManager.initCamera(RecorderManager.java:129)
        at com.mingyuechunqiu.recordermanager.ui.fragment.RecordVideoDelegate.startPreview(RecordVideoDelegate.java:95)
        at com.mingyuechunqiu.recordermanager.ui.fragment.RecordVideoDelegate.onSurfaceCreated(RecordVideoDelegate.java:395)
        at com.mingyuechunqiu.recordermanager.ui.fragment.RecordVideoFragment.surfaceCreated(RecordVideoFragment.java:189)
        at android.view.SurfaceView.updateWindow(SurfaceView.java:634)
        at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:162)
        at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2266)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1315)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6430)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:876)
        at android.view.Choreographer.doCallbacks(Choreographer.java:688)
        at android.view.Choreographer.doFrame(Choreographer.java:623)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:862)
        at android.os.Handler.handleCallback(Handler.java:754)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:163)
        at android.app.ActivityThread.main(ActivityThread.java:6276)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:788)

**Comment by MingYueChunQiu** [comment]
这个应该是相机参数设置错误，有可能是预览大小设置问题，我在红米note5a和小米9上测了一下没有问题。我优化了一下这块的逻辑，同时添加了拦截器功能，你可以直接试试用RecorderManagerFactory的newInstance(RecorderManagerInterceptable intercept)，传一个RecorderManagerIntercept，重写里面的 
/**
     * 拦截本机支持的相机预览大小参数设置
     *
     * @param list 本机支持的相机预览大小集合
     * @return 拦截不设置返回true，否则返回false
     */
    boolean interceptSettingPreviewSize(List<Camera.Size> list);

    /**
     * 拦截本机支持的相机图片大小参数设置
     *
     * @param list 本机支持的相机图片大小集合
     * @return 拦截不设置返回true，否则返回false
     */
    boolean interceptSettingPictureSize(List<Camera.Size> list);
来看看具体数据是怎么样的，用true返回不进行这两个方面的参数设置看看还有没有问题
