### ISSUE TITLE
调用最基本的,默认的视频录制,都直接崩溃了

### ISSUE THREAD

**Issue by wu410830911** [MingYueChunQiu/RecorderManager#22]
![image](https://user-images.githubusercontent.com/68216812/100043713-f18ced80-2e48-11eb-8f15-512b19549e4b.png)
![image](https://user-images.githubusercontent.com/68216812/100043749-036e9080-2e49-11eb-8cbe-a83db6cf0444.png)
-------------
在点击开始录制后,一直卡在00:01秒,再点一次停止播放,直接崩溃
-------------
    Stack trace :  
    java.lang.IllegalStateException
        at android.media.MediaRecorder.start(Native Method)
        at com.mingyuechunqiu.recordermanager.feature.record.RecorderHelper.recordVideo(RecorderHelper.java:164)
        at com.mingyuechunqiu.recordermanager.feature.record.RecorderManager.recordVideo(RecorderManager.java:87)
        at com.mingyuechunqiu.recordermanager.feature.main.detail.RecordVideoPresenter.startRecordVideo(RecordVideoPresenter.java:200)
        at com.mingyuechunqiu.recordermanager.feature.main.detail.RecordVideoPresenter.pressToStartRecordVideo(RecordVideoPresenter.java:143)
        at com.mingyuechunqiu.recordermanager.feature.main.detail.RecordVideoFragment$1.onPreProgress(RecordVideoFragment.java:83)
        at com.mingyuechunqiu.recordermanager.ui.widget.CircleProgressButton.onTouchEvent(CircleProgressButton.java:84)
        at android.view.View.dispatchTouchEvent(View.java:11776)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2600)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2600)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2600)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2600)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2600)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2600)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2600)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2600)
        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:448)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1829)
        at android.app.Activity.dispatchTouchEvent(Activity.java:3307)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:410)
        at android.view.View.dispatchPointerEvent(View.java:12015)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4795)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4609)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4147)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4200)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4166)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4293)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4174)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4350)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4147)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4200)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4166)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4174)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4147)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6661)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6635)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6596)
2020-11-24 11:29:11.100 4135-4135/com.qyz.qyz E/TLog:     at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6764)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:186)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:325)
        at android.os.Looper.loop(Looper.java:142)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by MingYueChunQiu** [comment]
请问是什么手机及系统版本，可否尝试将所有相关权限添加完整试试，或者直接调用库里录音功能试下有没有异常，或者直接原生
`mRecorder = new MediaRecorder();
        mRecorder.setAudioSource(MediaRecorder.AudioSource.MIC);
        mRecorder.setOutputFormat(MediaRecorder.OutputFormat.THREE_GPP);
        mRecorder.setOutputFile(mFileName);
        try {
            mRecorder.prepare();
        } catch (IOException e) {
            Log.e(LOG_TAG, "prepare() failed"+"..=="+e.toString());
        }
        
//         try{
         mRecorder.start();
//         }catch (IllegalStateException e)
//         {
//          startRecording();
//          Log.e(LOG_TAG, "start() failed"+"..=="+e.toString());
//         }`
试试有没有问题，看是否是库的问题
