### ISSUE TITLE
java.lang.IllegalStateException 	at android.media.MediaRecorder.start(Native Method)

### ISSUE THREAD

**Issue by droidsde** [MingYueChunQiu/RecorderManager#32]
误碰录制按钮，再次点录制按钮闪退

Process Name: 'com.sj.navi.demo'
Thread Name: 'main'
Back traces starts.
java.lang.IllegalStateException
	at android.media.MediaRecorder.start(Native Method)
	at com.mingyuechunqiu.recordermanager.feature.record.RecorderHelper.recordVideo(RecorderHelper.java:167)
	at com.mingyuechunqiu.recordermanager.feature.record.RecorderManager.recordVideo(RecorderManager.java:89)
	at com.mingyuechunqiu.recordermanager.feature.main.detail.RecordVideoPresenter.startRecordVideo(RecordVideoPresenter.kt:148)
	at com.mingyuechunqiu.recordermanager.feature.main.detail.RecordVideoPresenter.pressToStartRecordVideo(RecordVideoPresenter.kt:98)
	at com.mingyuechunqiu.recordermanager.feature.main.detail.RecordVideoFragment$1.onPreProgress(RecordVideoFragment.java:112)
	at com.mingyuechunqiu.recordermanager.ui.widget.CircleProgressButton.onTouchEvent(CircleProgressButton.java:84)
	at android.view.View.dispatchTouchEvent(View.java:11776)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2600)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2600)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2600)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2600)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2600)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2600)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2600)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:448)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1829)
	at android.app.Activity.dispatchTouchEvent(Activity.java:3307)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:410)
	at android.view.View.dispatchPointerEvent(View.java:12015)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4795)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4609)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4147)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4200)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4166)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4293)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4174)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4350)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4147)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4200)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4166)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4174)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4147)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6661)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6635)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6596)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6764)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:186)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:325)
	at android.os.Looper.loop(Looper.java:142)
	at android.app.ActivityThread.main(ActivityThread.java:6494)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Back traces ends.

**Comment by MingYueChunQiu** [comment]
能具体描述一下操作流程吗，误触是什么意思，是没注意按了按钮，又长按录制导致问题吗

**Comment by droidsde** [comment]
我重现了几次，有可能是audiorecord和mediarecord有资源冲突，因为我的项目里面有audiorecord的录音

**Comment by droidsde** [comment]
完整复现了，多次重复录音，会出现

**Comment by MingYueChunQiu** [comment]
你是指多次使用库的录音功能会导致问题，不是录制视频模块？

**Comment by droidsde** [comment]
音频录音，反复录音，我试了一下单例问题，录音使用单例，可能存在资源释放不到位，单独把录音的代码拿出来使用没问题

**Comment by MingYueChunQiu** [comment]
录音功能的使用，调用api时，会返回boolean值表示是否开始录制，需要外部控制进行资源释放，目前没做资源控制，后期有空看下是否需要库做控制
